# TODO this was generated by my intern, need to dbg and check

# ADAPTED FROM
# https://github.com/uncomtrade/comtradeapicall/blob/main/tests/example%20calling%20functions%20-%20notebook.ipynb

# Load necessary libraries
library(httr)
library(data.table)

# Load environment variables
load_dotenv()

# Set subscription key
subscription_key <- Sys.getenv("comtrade_user_subscription_key")

# Output directory for downloaded files
data_directory <- './data'

# Set time-related variables
today <- Sys.Date()
yesterday <- today - 1
lastweek <- today - 7

# Get cbam data
cbam_hs_df <- fread(paste0(data_directory, '/cbam_hs.csv'))

# Set up HS codes
cbam_hs <- paste(cbam_hs_df$`HS 6-digit (text)`, collapse = ',')

cbam_sectors <- unique(cbam_hs_df$`CBAM Sector`)

cbam_sectors_hs <- list()

for (s in cbam_sectors) {
  num_products <- sum(cbam_hs_df$`CBAM Sector` == s)
  if (num_products <= 100) {
    cbam_sectors_hs[[s]] <- paste(cbam_hs_df$`HS 6-digit (text)`[cbam_hs_df$`CBAM Sector` == s], collapse = ',')
  } else {
    cat(sprintf('Too many HS codes for the UN API to handle (%d). Splitting into chunks...\n', num_products))
    for (chk in seq(0, num_products + 1, 100)) {
      chk_name <- sprintf('%s_%d', s, chk)
      cat(sprintf('%s\n', chk_name))
      chunk_upper_lim <- chk + 100
      if (chunk_upper_lim > (num_products + 1)) {
        chunk_upper_lim <- num_products + 1
      }
      cbam_sectors_hs[[chk_name]] <- paste(cbam_hs_df$`HS 6-digit (text)`[cbam_hs_df$`CBAM Sector` == s][seq(chk, chunk_upper_lim)], collapse = ',')
    }
  }
}

# Set up timeframe
start_year <- 2015
end_year <- 2023

years_desired <- paste(start_year:end_year, collapse = ',')

# Set up desired jurisdictions
un_country <- fread(paste0(data_directory, '/UNSD_Methodology.csv'), sep = ';')

un_country_m49_all <- paste(un_country$`M49 Code`, collapse = ',')

un_country_m49_chunks <- list()

chunk_size <- 50

for (chk in seq(0, nrow(un_country) + 1, 50)) {
  chk_name <- sprintf('m49_%d', chk)
  chunk_upper_lim <- chk + 50
  if (chunk_upper_lim > (nrow(un_country) + 1)) {
    chunk_upper_lim <- nrow(un_country) + 1
  }
  cat(sprintf('%s\n', chk_name))
  un_country_m49_chunks[[chk_name]] <- paste(un_country$`M49 Code`[seq(chk, chunk_upper_lim)], collapse = ',')
}

request_params <- list(
  subscription_key = subscription_key,
  typeCode = 'C',  # C commodities; S service
  freqCode = 'A',  # A annual; M monthly
  clCode = 'HS',   # HS; SITC; BEC; EBOPS
  period = 2020,   # year or month in form YYYY or YYYYMM respectively # will add that in loop later on
  reporterCode = '36',  # M49 code of countries, csv
  #cmdCode = cbam_hs, #'91', #your HS codes
  flowCode = 'M',   # rest of the params aren't listed on the param explanation page, lol
  partnerCode = NULL,
  partner2Code = NULL,
  customsCode = NULL,
  motCode = NULL,
  maxRecords = NULL,
  format_output = 'JSON',
  #aggregateBy = NULL,
  #breakdownMode = 'classic',
  countOnly = NULL,
  includeDesc = TRUE
)

# Basic example of API call
# cbam_df <- comtradeapicall::previewFinalData(**request_params)

# Iterating over jurisdiction chunks

# Iterating over commodity groups
cbam_data_by_commodity <- list()

cbam_data_all <- data.table()
failed_requests <- list()

for (cmdty in names(cbam_sectors_hs)) {
  cat(sprintf('Starting request for %s\n', cmdty))
  _request_params <- request_params
  _request_params$period <- years_desired
  _request_params$cmdCode <- cbam_sectors_hs[[cmdty]]
  cbam_data_m49_chunks <- list()
  for (chk in names(un_country_m49_chunks)) {
    cat(sprintf('Starting request for %s\n', chk))
    _request_params$reporterCode <- un_country_m49_chunks[[chk]]
    tryCatch({
      request_df <- comtradeapicall::getTarifflineData(**_request_params)
    }, error = function(e) {
      cat('Request failed successfully! (ie it didn\'t work)\n')
      cat(sprintf('%s\n', e))
      request_df <- data.table()
      failed_requests[[cmdty]] <- chk
    })
    cbam_data_m49_chunks[[chk]] <- request_df
    cbam_data_all <- rbindlist(list(cbam_data_all, request_df))
    fwrite(cbam_data_all, paste0(data_directory, '/cbam_data_all.csv'))
  }
  cbam_data_by_commodity[[cmdty]] <- cbam_data_m49_chunks
}
